name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        A clear and well-defined request makes it easier for contributors to understand and implement.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Explain the feature or improvement you are suggesting.
      placeholder: I would like netora to be able to...
    validations:
      required: true
  - type: checkboxes
    id: agreement
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow the project's [Code of Conduct](../../docs/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true